server:
  port: 443

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongo uri
      database: The-Museum-Cinemaya-Dev

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongo uri
      database: The-Museum-Cinemaya-Prod
